### ISSUE TITLE
Create initial Azure function project with sample functions

### ISSUE THREAD

**Issue by wobba** [CrayonAS/Cumulus#3]
Create initial project with a sample of generic functions. Use Puzzlepart code as starting point.

Would it be smart with a separate repo for this? @kjetilg @janegilring

**Comment by kjetilg** [comment]
Does it help with CI/CD if it’s a separate repo? If yes then yes, as it would be cool if one could just point the function app to the repo and deploy from there 😊

**Comment by janegilring** [comment]
It makes sense to be able to point to a repo in order to deploy.
But I`m not following along the Repo.Technology naming vs Repo.Product...can anyone expand on this?

**Comment by wobba** [comment]
Cumulus.Provisioning.Helpers then. Whatever :) or Helpers... You figure out
a smart naming convention and I'm all for it.

**Comment by wobba** [comment]
Just let me know when it's done :)

**Comment by janegilring** [comment]
[Here](https://github.com/CrayonAS/Cumulus.Monads) you go.

**Comment by olemp** [comment]
https://github.com/CrayonAS/Cumulus.Monads
